Homework04 - HW Pandas Intro

By Antoaneta Chakarova for Geog592

09/13/2026

In [21]:
import pandas as pd
df = pd.read_csv("C:/Users/Tony/Documents/Fall2026/Geog592/geog592-achakaro/homework/week04/data/streamflow_clean.csv")
df.head()

         Station        Date  Discharge  Longitude  Latitude
0  USGS-02068500  2021-01-01      357.0 -80.303056    36.515
1  USGS-02068500  2021-01-02      426.0 -80.303056    36.515
2  USGS-02068500  2021-01-03      374.0 -80.303056    36.515
3  USGS-02068500  2021-01-04      356.0 -80.303056    36.515
4  USGS-02068500  2021-01-05      316.0 -80.303056    36.515

In [22]:
df.shape

(3285, 5)

In [23]:
df.columns

Index(['Station', 'Date', 'Discharge', 'Longitude', 'Latitude'], dtype='object')

In [24]:
df.dtypes

Station       object
Date          object
Discharge    float64
Longitude    float64
Latitude     float64
dtype: object

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3285 entries, 0 to 3284
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Station    3285 non-null   object
 1   Date       3285 non-null   object
 2   Discharge  3285 non-null   float64
 3   Longitude  3285 non-null   float64
 4   Latitude   3285 non-null   float64
dtypes: float64(3), object(2)
memory usage: 128.4+ KB

In [ ]:
mask = df["Station"] == "USGS-02097517" #Morgan creek in chapel hill
df_chapel_hill = df[mask]

df_chapel_hill.head()

            Station        Date  Discharge  Longitude   Latitude
1095  USGS-02097517  2021-01-01       78.7 -79.019722  35.893333
1096  USGS-02097517  2021-01-02      239.0 -79.019722  35.893333
1097  USGS-02097517  2021-01-03      755.0 -79.019722  35.893333
1098  USGS-02097517  2021-01-04      181.0 -79.019722  35.893333
1099  USGS-02097517  2021-01-05      106.0 -79.019722  35.893333

In [27]:
df_chapel_hill.shape

(1095, 5)